[build]
  command = "flutter build web --wasm"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/**"
  [headers.values]
    Content-Encoding = "br"
    Cache-Control = "public, max-age=31536000, immutable"
